### ISSUE TITLE
Saved model 

### ISSUE THREAD

**Issue by limzh123** [VadymV/events_lifelong_learning#1]
Hi, 

I have some questions. May I know what is the format for the saved model? and how to execute this code? 

else:
        # Load previously trained model(s) (if goal is to only evaluate previously trained model)
        if verbose:
            print("\nLoading parameters of the previously trained models...")
        load_name = "mM-{}".format(param_stamp) if (
                not hasattr(args, 'full_ltag') or args.full_ltag == "none"
        ) else "{}-{}".format(model.name, args.full_ltag)
        utils.load_checkpoint(model, args.m_dir, name=load_name, verbose=verbose,
                              add_si_buffers=(isinstance(model, ContinualLearner) and utils.checkattr(args, 'si')))
        if generator is not None:
            load_name = "gM-{}".format(param_stamp) if (
                    not hasattr(args, 'full_ltag') or args.full_ltag == "none"
            ) else "{}-{}".format(generator.name, args.full_ltag)
            utils.load_checkpoint(generator, args.m_dir, name=load_name, verbose=verbose)

Thanks if you could assist me with this :)

**Comment by VadymV** [comment]
Hi.

1. The model is saved by calling the method `[torch.save()](https://pytorch.org/docs/stable/generated/torch.save.html)`
2. The code creates an identifier for the model that should be loaded (the code will only be executed if the model was trained and saved using the same configuration as for the model to be loaded).  

Hope this helps.

Best,
Vadym
